name: Generate Snake Animation

on:
  schedule: # roda automaticamente uma vez por dia
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Natan-Ledur
          outputs: dist/snake.svg

      - name: Push Snake to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generated Snake Animation"
          add: "dist/snake.svg"
